### ISSUE TITLE
Consistently unable to reveal bid on an address

### ISSUE THREAD

**Issue by davidkuchar** [ensdomains/ens#230]
I've been trying to buy an .eth address, and I'm unable to reveal it (I was able to purchase another name without any issues). I've opened the auction several times and each time the reveal button doesn't appear during the reveal period. Any thoughts on how to troubleshoot?

**Comment by flyswatter** [comment]
Is this an on-chain error, like `bad jump destination`? If so, I wish I knew better how to troubleshoot, but there are not currently great tools for stepping through & debugging on-chain errors.

If it's a different problem, please describe it.

**Comment by davidkuchar** [comment]
I dug in a little when it happened (was a couple weeks ago) and there appeared to be an error when the ens contract to reveal the bid was run. Let me dig it up.

**Comment by davidkuchar** [comment]
https://etherscan.io/tx/0x6f3b3ed90cab2f8e653d6a7ead0b015367ef3a1f0e345a5b896730e2d3031c45

**Comment by flyswatter** [comment]
Yeah, bad instruction is another kind of On-chain failure. I don't think there are currently great tools for diagnosing failures like this. I've posted that link to the name-registry gitter in case someone can decode it: Join the chat in ethereum/go-ethereum/name-registry
https://gitter.im/ethereum/go-ethereum/name-registry?utm_source=ios&utm_medium=link&utm_campaign=ios-share-link

**Comment by davidkuchar** [comment]
thanks @flyswatter

**Comment by troowala** [comment]
How did you end up resolving your issue pal ? For the life of me i cannot register an ENS domain with the same reveal issues on mainnet , ropsten works fine however.
