### ISSUE TITLE
FAQ „Trying to reveal too early“

### ISSUE THREAD

**Issue by asardon** [ensdomains/ens#277]
In the FAQ section „Why is my reveal transaction failing?“ this point seems incorrect:
„You’re trying to reveal too early“

In the unsealBid contract function no such check is made.

So shouldn‘t that troubleshooting point be removed?

**Comment by Arachnid** [comment]
The check is made in the `state` function, which returns `AUCTION` during the auction and `REVEAL` afterwards.
