### ISSUE TITLE
Failed execution consumed all gas - using revert() instead

### ISSUE THREAD

**Issue by vietlq** [ensdomains/ens#292]
Hi, I created a Tx before transferring ownership and as a result, I lost all gas allowance for the Tx:

https://etherscan.io/tx/0xa5481b76b847d6c27b0987758dda76d099c7d7bdac8bc36f3b90ac3385e1f48a

Is it possible to use `revert()` instead on failure so users in the future do not lose all gas? Thanks.

**Comment by Arachnid** [comment]
Hi,

The ENS registry was deployed before revert was available. We can't redeploy it without requiring everyone to migrate.

**Comment by vietlq** [comment]
Gotcha! :) Now it's known issue. Thanks for responding.

**Comment by vietlq** [comment]
Nick @Arachnid , out of curiousity I also have questions about future migrations. What's the upgrade path going forward if ENS decides to upgrade the registry?

**Comment by Arachnid** [comment]
If we *have* to, we can do so by creating a new registry, migrating all existing registrations over, and then getting clients to update. The registry was deliberately designed to be as simple as possible, though, to minimise the chance of that being required.

**Comment by vietlq** [comment]
How does this part work:

> migrating all existing registrations over

You would insert/pre-populate state when initialising the new contract (if it ever happens)?

**Comment by Arachnid** [comment]
Either we'd submit transactions adding all the keys from the original ENS registry, or we'd make the new registry fall back to the old one.
