### ISSUE TITLE
Auction structure ideas for shorter names.

### ISSUE THREAD

**Issue by scott-l-e-w-i-s** [ensdomains/ens#300]
One of the issues with the last .eth unveiling was the starting gun format (dampened by the smart hash-dependent starting slope over weeks).

A suggestion for an alternative auction structure: Rather than auctioning a specific name, you auction ERC-721s that represent the right to register a name on any block after block X.

Assume the new registration period starts on block 100. Rather than bidding on poker.eth, you would bid on a >99 token, >100 token, >101 token, etc. By funneling everyone to bid on registration order, rather than individual names, I think you get a handful of advantages:

 - net mental load would be reduced for all. Rather than pricing each and every word, you must only price the curve of domain values and also pick your favorite remaining word.
 - fair prices. since order tokens are easy to price relative to other order tokens, less sophisticated users can be more confident they are getting a fair price for the domain they want, boosting participation.
 - no names scooped on the sly. Last auction, if there was a name that was good, but not in the cached list of domain name hashes, a sneaky bidder could scoop it for the minimum bid.
 - no free-riding squatters. when I bid on a name for the first time, because i want it.. a squatter can see the recently open auctions and start bidding, having been pointed in the right direction.
  - eliminate the need for the somewhat economically inefficient decoy deposits in the last round.

**Comment by Arachnid** [comment]
Thanks for the feedback! Can you post this on https://discuss.ens.domains/, where people can see and comment on it?
