### ISSUE TITLE
Controller not defined in README

### ISSUE THREAD

**Issue by tjayrush** [ensdomains/ens#315]
This page

https://github.com/ensdomains/ens/blob/ethregistrar/docs/ethregistrar.rst

has a great terminology section near the beginning that defines various terms. Very helpful. 

In the section immediately following that, the term ‘controller’ appears without any introduction or definition. Suggestion: add a definition for the term ‘controller’, or if the same concept is defined above use the name of that concept, not ‘controller’.

**Comment by Arachnid** [comment]
Thanks! I've fixed this.
