### ISSUE TITLE
How the old auction registrar became inoperable?

### ISSUE THREAD

**Issue by xwartz** [ensdomains/ens#331]
I know the new registrar has launched at May 4, 2019, and the old registrar has became inoperable, but I have some questions.

1. How did you affect this contract [0x6090a6e47849629b7245dfa1ca21d94cd15878ef](https://etherscan.io/address/0x6090a6e47849629b7245dfa1ca21d94cd15878ef#code)? 
I did not see any instruction on the official documentation.

2. Is it just that `startAuction` function is not available, other operations(`newBid`, `finalizeAuction`...)?

**Comment by Arachnid** [comment]
The owner of 'eth' in the ENS registry was changed to the new registrar. This made the old registrar incapable of making changes.

Please feel free to ask more questions like this in our discussion group at https://discuss.ens.domains/.
