### ISSUE TITLE
Register Domains

### ISSUE THREAD

**Issue by NickTheLim** [ensdomains/ens#337]
How are domains registered programatically via an API?

**Comment by Arachnid** [comment]
Please see https://docs.ens.domains/dapp-developer-guide/registering-and-renewing-names

**Comment by NickTheLim** [comment]
Any documentation on how to interact with the .eth registrar via one of those libraries?

**Comment by Arachnid** [comment]
There aren't libraries specifically for interacting with the registrar, but you can use a standard web3 library for interacting with the contracts.
