### ISSUE TITLE
EXPIRATION DATE 2020.11.05

### ISSUE THREAD

**Issue by rfikki** [ensdomains/ens#348]
Just a heads-up: UI question regarding ens.domains website, many casual users in the USA might mistakenly think this expiration means November 05, 2020! "EXPIRATION DATE 2020.11.05 at 21:40"
![expiration](https://user-images.githubusercontent.com/1055929/75084790-4a111200-54e8-11ea-8fbf-1f5b52530c30.JPG)

**Comment by Arachnid** [comment]
Really? I know the US uses mm/dd/yyyy, and the rest of the world uses dd/mm/yyyy, but these are ISO format dates - yyyy/mm/dd. I don't think anyone's insane enough to use yyyy/dd/mm.

**Comment by rfikki** [comment]
Just google: "2020 11 05"
