### ISSUE TITLE
ETH is the ISO for Ethiopia

### ISSUE THREAD

**Issue by ca98am79** [ensdomains/ens#372]
As I am aware, the top level domain .eth has been reserved by ICANN because it is the ISO for Ethiopia

Isn't this a potential collision and therefore against the ENS stated goal of [Responsible Citizenship in the Global Namespace](https://medium.com/the-ethereum-name-service/why-ens-doesnt-create-more-tlds-responsible-citizenship-in-the-global-namespace-7e66658fe2b1) ?

By not allowing other TLDs (e.g. [Handshake](https://handshake.org/)), isn't this just pretense and posturing?

One way to potentially resolve this is to append a TTLD (TOP top level domain).  For example .eth.icann and .eth.ethereum, something like this.  Or (preferably) ENS could abandon the idea that they must "bend the knee" to ICANN, which centralizes the system anyway, and therefore IMO takes away a lot/all of the value of using Ethereum for domain names in the first place.

I think it is a mistake for ENS to position as Responsible Citizenship in the Global Namespace on one hand, and at the same time try to use the top level domain .eth - it is in direct opposition to each other.

**Comment by Arachnid** [comment]
We weren't aware of .eth being reserved as a 3-letter country code when we first launched; if we were we likely would have picked something different. At this point it's no longer practical to change, but we can do our best to be good citizens going forward.

Questions like this are better suited to the ENS Discourse forum: https://discuss.ens.domains/
