### ISSUE TITLE
AbstractPublicResolver smart contract is not used

### ISSUE THREAD

**Issue by 3sGgpQ8H** [ensdomains/ens#61]
It seems that AbstractPublicResolver smart contract is never user.  Also this smart contract looks very odd in general.

**Comment by Arachnid** [comment]
This is an interface contract - it allows people to get a generic interface for a 'public resolver' by importing this into their Solidity code, without having to import the implementation of a specific resolver as well.

**Comment by mikhail-vladimirov** [comment]
If what you said is the case, then why PublicResolver does not inherit this interface and why this interface defines functions PublicResolver(address), hash(bytes32), and setHash(bytes32, bytes32) which PublicResolver actually does not have?

**Comment by Arachnid** [comment]
PublicResolver doesn't _have_ to implement the interface, but you're right, it should. Reopening to remind me to fix that.
